server:
  port: 9090

spring:
  application:
    name: ApiGateWay


  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
springdoc:
  swagger-ui:
    urls:
      - name: CustomerService
        url: /CustomerService/v3/api-docs



#springdoc:
#  swagger-ui:
#    urls:
#      - name: program-manager
#        url: http://localhost:8081/v3/api-docs
#      - name: enrolment-manager
#        url: http://localhost:8084/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: '*'
