server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customer-service/**
              filters:
                - StripPrefix=1
            - id: account-service
              uri: lb://account-service
              predicates:
                - Path=/account-service/**
              filters:
                - StripPrefix=1
            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/transaction-service/**
              filters:
                - StripPrefix=1
            - id: transaction-service
              uri: lb://transaction-service
              predicates:
                - Path=/transaction-service/**
              filters:
                - StripPrefix=1
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: account-service
        url: /account-service/v3/api-docs
      - name: transaction-service
        url: /transaction-service/v3/api-docs
      - name: transaction-service
        url: /transaction-service/v3/api-docs
      - name: customer-service
        url: /customer-service/v3/api-docs
