server:
  port: 8081

spring:
  application:
    name: CustomerService

  datasource:
    url: jdbc:mysql://localhost:3306/customers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true